name: solana_token_list
version: 0.1.0
description: Solana Token Registry is a package that allows application to query for list of tokens.
homepage: https://github.com/kecson/solana_token_list

topics:
  - solana

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.25.8

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0

false_secrets:
  - /lib/src/static_tokens.dart
