name: solana_token_list
version: 0.0.3
description: Solana Token Registry is a package that allows application to query for list of tokens.
homepage: https://github.com/kecson/solana_token_list

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  build_runner: ^2.1.2
  lints: ^1.0.1
  test: ^1.16.0

dependencies:
  http: ^0.13.3
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2
