name: solana_token_list
description: Solana Token Registry is a package that allows application to query for list of tokens. The JSON schema for the tokens includes chainId, address, name, decimals, symbol, logoURI (optional), tags (optional), and custom extensions metadata.
version: 0.0.2
homepage: https://github.com/kecson/solana_token_list

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  test: ^1.16.0
  build_runner: ^2.1.2

dependencies:
  http: ^0.13.3
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2
